// LOCALHOST
###
GET http://localhost:3000/students

###
GET http://localhost:3000/students/67296f1b4ea7b766a3a3fdb2

###
GET http://localhost:3000/students/673222afcd9a4ccf67f24318
###
GET http://localhost:3000/students/673222f3cd9a4ccf67f3446c

### Create contact 
POST http://localhost:3000/students HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley", 
    "lastName":"Weaver", 
    "email":"aWeaver@test.com",
    "number":19
}

###
PUT http://localhost:3000/students/67322e4abc02c9ab21c8fcb5 HTTP/1.1
content-type: application/json

{
    "firstName":"Ashlee", 
    "lastName":"Weaver", 
    "email":"aWeaver@test.com",
    "number":19
}

###
DELETE http://localhost:3000/students/673230f03519bf981ba85cc7 HTTP/1.1

// PRODUCTION Deploy
###
GET https://webservices-w05.onrender.com/students
###
GET https://webservices-w05.onrender.com/students/67296f1b4ea7b766a3a3fdb2
###
GET https://vangricky-api.onrender.com/contacts/673222afcd9a4ccf67f24318
###
GET https://vangricky-api.onrender.com/contacts/673222f3cd9a4ccf67f3446c

### Create contact 
POST https://webservices-w05.onrender.com/students HTTP/1.1
content-type: application/json

{
  "firstName": "Leanne",
  "lastName": "Graham",
  "email": "leanneg@gmail.com",
  "number": 22
}

###
PUT https://webservices-w05.onrender.com/students/6732331fa087742162438df0 HTTP/1.1
content-type: application/json

{
  "firstName": "Lean",
  "lastName": "Graham",
  "email": "leanneg@gmail.com",
  "number": 22
}

###
DELETE https://webservices-w05.onrender.com/students/6732331fa087742162438df0 HTTP/1.1